### PR TITLE
Leptos v0.6.5

### LINKED ISSUE #36: Update to Leptos v0.5.0
Changelog (Goodby `Scope`) https://github.com/leptos-rs/leptos/releases/tag/v0.5.0

### PR DESCRIPTION
**Pull request by sectore**
incl. `nix flake update`

~~Note: Upstreams needs to be updated to latest Leptos, too:~~
   - ~~https://github.com/bankai-labs/leptos-icons/~~ *removed*
   - ~~https://github.com/elsirion/leptos-qr-scanner~~ *done*

Closes #36

### CODE REVIEW

**Review by elsirion — APPROVED** [review]

**Comment by HaosGames** [comment]
If https://github.com/bankai-labs/leptos-icons/ isn't going to be updated anymore maybe a switch to https://github.com/Carlosted/leptos-icons could be done.

**Comment by ngutech21** [comment]
leptos-qr-scanner has been updated and supports leptos 0.6: 5830bd6f75d7836189ef1434f71a10222a737a44
leptos 0.6 didn't change the client api, so the upgrade from 0.5 should be easy. If the leptos-icons lib gets replaced as proposed by @HaosGames  I think webimint could be upgraded.

**Comment by elsirion** [comment]
Yep, just need to find the time to get back to webimint, but Fedimint is keeping me rather busy these days.

**Comment by sectore** [comment]
With latest update of 6df204a the build failed with different errors, mostly thrown by Leptos `server_fn-0.6.5` crate  (see [build logs from line 1098](https://github.com/elsirion/webimint-rs/actions/runs/7862489259/job/21452032323?pr=40#step:6:1099). Do we need to update the Rust version? If so, how do to that with `fedimint`'s flake?

**Comment by elsirion** [comment]
> Do we need to update the Rust version? If so, how do to that with `fedimint`'s flake?

We can't just update the fedimint flake input since fedimint itself is still on rust 1.73 while we need 1.75. It might be worth setting up [flakebox](https://github.com/rustshop/flakebox) directly for webimint instead of relying on fedimint.

**Comment by sectore** [comment]
Using `Flakebox` introduced by #56, everything compiles now. Please merge #56 before this PR here.

```bash
trunk serve

2024-02-12T14:10:38.760781Z  INFO ✅ success
2024-02-12T14:10:38.763043Z  INFO 📡 serving static assets at -> /
2024-02-12T14:10:38.763055Z  INFO 📡 server listening at http://127.0.0.1:8080
```
```bash
trunk build --release

2024-02-12T14:14:15.501822Z  INFO ✅ success
```

**Comment by elsirion** [comment]
Seems like merging #56 first lead to some merge conflicts :grimacing:

**Pull request merged**
